name: Bitwise Tests

# Run workflow on pushes to the bitwise directory or this workflow file
on:
  push:
    paths:
      - 'bitwise/**' # Run workflow when files in the bitwise folder change
      - '.github/workflows/bitwise-tests.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Dependency installation is commented out because these tools are pre-installed on 'ubuntu-latest'.
      # Uncomment the step if you need to ensure specific versions of cmake or build-essential.
      # - name: Install dependencies
      #   run: sudo apt update && sudo apt install -y cmake build-essential ninja-build

      # Build the project
      - name: Build bitwise project
        run: |
          cmake -S bitwise -B bitwise/build -G Ninja -DCMAKE_C_COMPILER=${{ matrix.compiler }}
          cmake --build bitwise/build

      # Run tests with ctest
      - name: Run tests
        run: |
          cd bitwise/build
          ctest --output-on-failure

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}
          path: bitwise/build/Testing
