name: Bitwise Tests


# Kör workflow när det pushas
on:
  push:
    paths:
      - 'bitwise/**' # Kör denna workflow när filer i bitwise-mappen ändras
      - '.github/workflows/bitwise-tests.yml'
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Använder en Ubunut-maskin av senaste slag

    steps:
      # Checka ut koden
    - name: Chekout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake build-essential


    # Bygg projektet
    - name: Build bitwise project
      run: |
        cd bitwise
        mkdir -p build
        cd build
        cmake ..
        cmake --build .

    # Kör tester med ctest
    - name: Run tests
      run: |
        cd bitwise/build
        ctest --verbose
