name: Bitwise Tests


# Kör workflow när det pushas
on:
  push:
    paths:
      - 'bitwise/**' # Kör denna workflow när filer i bitwise-mappen ändras
      - '.github/workflows/bitwise-tests.yml'
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Använder en Ubunut-maskin av senaste slag
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checka ut koden
    - name: Chekout code
      uses: actions/checkout@v2

    # Ställ in CMake
    - name: Set up CMake
      uses: lukka/setup-cmake@v1
      with:
        cmake-version: '3.16' # Ange CMake version

    # Bygg projektet
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    # Kör tester med ctest
    - name: Run tests
      run: |
        cd build
        ctest --verbose
