name: Led Controller Build

on:
  push:
    paths:
      - 'led_controller/**'
      - '.github/workflows/led-controller.yml'

jobs:
  build:
    uses: ./.github/workflows/firmware-build.yml
    with:
      name: led_controller
      rename: led-controller
      ext: "bin uf2 elf"
