name: Led Controller Build

on:
  push:
    paths:
      - 'led_controller/**'
      - '.github/workflows/led-controller.yml'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y \
          build-essential \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi \
          libstdc++-arm-none-eabi-newlib

      - name: Fetch pico-sdk
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git checkout 2.1.1 #Lås versionen
          git submodule update --init
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Configure CMake
        working-directory: led_controller
        run: cmake -B build -G Ninja

      - name: Build Led Controller
        working-directory: led_controller
        run: cmake --build build

      - name: List built files
        working-directory: led_controller
        run: ls -l build || true

      - name: List built files in bin
        working-directory: led_controller
        run: ls -l bin || true

      - name: Upload firmware as artifacts
        working-directory: led_controller
        uses: actions/upload-artifact@v4
        with:
          name: pico-firmware
          path: |
            bin/*.elf
            bin/*.uf2
            build/*.elf
            build/*.uf2
